heat_template_version: 2016-10-14

description:
  An instance for a DNS slave server
  The instances are created with Heat and then configured with Ansible

parameters:
  slave_count:
    type: number
    description: >
      Number of slave servers to create.
    default: 3

  service_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  service_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

resources:
  
  slaves:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: slave_count}
      resource_def:
        type: one_slave.yaml
#        properties:
#          service_network: {get_param: service_network}
#          service_subnet: {get_param: service_subnet}
          

