heat_template_version: 2016-10-14

description:
  A simple network to host other services

parameters:
# Networks to connect to or create
  external_network:
    type: string
    description: >
      The external network that provides floating IP addresses for the nodes
    constraints:
    - custom_constraint: neutron.network

  service_subnet_cidr:
    type: string
    description: >
      The subnet used for instance to instance communication
    default: 192.168.0.0/24

  dns_nameservers:
    type: comma_delimited_list
    description: Addresses of a dns nameserver reachable in your environment
    default: 8.8.8.8

resources:

  # Network Components
  service_network:
    type: OS::Neutron::Net

  service_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: service_subnet_cidr}
      network: {get_resource: service_network}
      dns_nameservers: {get_param: dns_nameservers}

  external_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: external_network}

  external_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: external_router}
      subnet: {get_resource: service_subnet}

