---
- name: Deploy the DNS servers
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - name: Create the Heat Stack
    os_stack:
      name: "{{ stack_name }}"
      template: dns_service.yaml
      parameters:
        domain_name: "{{ domain_name | default('example.com') }}"
        external_network:  "{{ external_network }}"
        ssh_key_name: "{{ ssh_key_name }}"
        dns_forwarders: "{{ dns_forwarders }}"
        image: "{{ image }}"

        slave_count: "{{ slave_count | default(3) }}"
        slave_server_group_policies: "{{ slave_server_group_policies }}"

    register: stack_output

  - debug: var=stack_output


- include: ansible/bind-server.yml
