heat_template_version: 2016-10-14

description:
  An instance for a DNS slave server
  The instances are created with Heat and then configured with Ansible

parameters:

  # Connectivity
  service_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  service_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  # Host Characteristics
  hostname:
    description: The prefix for slave nameserver hostnames
    type: string

  server_group:
    description: >
      ID of a server group containing all of the master hosts
    type: string

resources:
  host:
    type: OS::Nova::Server
    properties:
      image: rhel7
      flavor: m1.small
      networks:
      - port: {get_resource: port}
      name: {get_param: hostname}
      scheduler_hints:
        group: {get_param: server_group}
        
  port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: service_network}
      fixed_ips:
      - subnet: {get_param: service_subnet}
      replacement_policy: AUTO
