:gitroot: https://github.com/markllama

== DNS Service for OpenStack with Heat

This repository defines a simple distributed DNS service within an
OpenStack Heat stack.  The goal is to de-mystify DNS services and
deployments for low level delegated sub-domains.  It is NOT to provide
enterprise scale and quality DNS services.

The service deployed will include


== Deployment Procedure

The `full-service.yaml` Ansible playbook uses OpenStack Heat to deploy
the VMs and set up networking. Once the servers are accessible, it
installs the dependencies and sets up BIND in a master/slave
configuration.


=== Get the GIT repository

.Clone the Heat and Ansible repositories

[subs=attributes]
----
git clone {gitroot}/dns-service-heat.git
----

=== Input Values

You will need to prepare a few inputs that we can't detect
automatically.

NOTE: you can take a look at `vars.sample.yaml`.

==== Required Values

DOMAIN NAME / ZONE::
  The DNS zone to be served. +
  Type: string +
  Example: `example.com`

DNS_FORWARDERS::
  The upstream DNS servers. Any domain outside of the `domain_name` above will be forwarded to one of these servers. +
  Type: list +
  Example: `[8.8.8.8, 8.8.4.4]`

If you're not sure what to put here, a good start might be the values from your own `/etc/resolv.conf`:

----
$ grep '^\s*nameserver.*$' /etc/resolv.conf | awk '{print $2}'
----

DNS_UPDATE_KEY::
  A symmetric key value for dynamic DNS updates +
  Type: string +
  This is a BASE64 encoded MD5 hash, randomly generated by
  `ddns-confgen(8)`.

The `ddns-confgen` is installed alongside `bind-utils` and to generate the key, you can do this:

----
$ ddns-confgen -r /dev/urandom | grep secret
----

The key should look something like this:

----
VXQsVJgDtEj1CFPjnt/OK3ilgJyAzT6OeY9CDoqa0/Q=
----

NOTE: anyone with this key will be able to update the entries in your
DNS server. Treat it as secret.

EXTERNAL_NETWORK_NAME::
  The name of an existing Neutron network in the OSP environment which
  allows inbound and outbound traffic. +
  Type: string +
  Example: `ext-net`

KEYPAIR_NAME::
  The name of an existing Nova keypair +
  Type: string +
  Example: `ocp_key`

==== Optional Values

== Deploying the DNS stack

Assuming you put your configuration in `vars.yaml` and you're using a
CentOS image:

----
$ ansible-playbook --user centos full-service.yaml -e @vars.yaml
----

If you're deploying Fedora, you must set `--user fedora` and for the newer versions pass this in:

----
-e 'ansible_python_interpreter=/usr/bin/python3'
----

(Ansible uses Python on the target servers and later Fedoras only have
Python3 installed by default.)

== Setting the DNS entries from an OSP heat stack

This stack is, in the end targeted for use by an OpenShift service
installed on openstack.  The openshift-ansible installation process
depends on the existance of a DNS A record for each instance in the
OpenShift cluster.  Instances which also have a floating IP address
get a second DNS A record for the public name.

These two scripts below extract the hostname and IP addresses of the O

----
 python bin/ocp_host_info.py -S <stack name> --zone <zone> > osp_host_spec.yaml
 DNS_UPDATE_KEY="not a real key" # if not already set
 python bin/prime_zones.py -s <nameserver ip>  osp_host_spec.yaml

----

== Requirements

* python2
* python-openstackclient
* python-dns [RHEL7]
* python2-dns [Fedora]
* python-jinja
* jq
