:gitroot: https://github.com/markllama

== DNS Service for OpenStack with Heat

This repository defines a simple distributed DNS service within an
OpenStack Heat stack.  The goal is to de-mystify DNS services and
deployments for low level delegated sub-domains.  It is NOT to provide
enterprise scale and quality DNS services.

== Deployment Procedure

The stack is deployed using a set of Heat templates and an Ansible
playbook driven by a BASH script. In the future these will be
collapsed so the entire process is driven by Ansible.  For now a small
amount of glue code is still required.

=== Get the GIT repository

.Clone the Heat and Ansible repositories

[subs=attributes]
----
git clone {gitroot}/dns-service-heat.git
git clone {gitroot}/dns-service-playbooks.git
----

=== Input Values

ZONE:
  The DNS zone to be served +
  Type: string
  Example: `example.com`

DNS_UPDATE_KEY::
  A symmetric key value for dynamic DNS updates +
  Type: string +
  This is a BASE64 encoded MD5 hash, randomly generated by
  `rndc-confgen(8)`.

SERVER_SPEC_FILE::
  The name of a YAML file containing the Nova instance specification values. +
  Example: +
  `parameters: +
    flavor: m1.small +
    image: rhel73 +
    ssh_user: cloud-user`
  



